[package]
name = "tmux-revive"
version = "0.1.0"
authors = ["graelo <graelo@grael.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4"
futures = "0.3"
tokio = { version = "1.4", features = ["fs", "macros", "process", "rt-multi-thread"] }
