[package]
name = "tmux-revive"
version = "0.1.0"
authors = ["graelo <graelo@grael.cc>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
thiserror = "1"

log = "0.4.17"
regex = "1.4"

futures = "0.3"
async-std = { version = "1", features = ["unstable"] }

tar = "0.4.38"
zstd = "0.11.2"
