# Runs cargo-outdated when the `check-outdated` label is added to a PR

name: Check outdated dependencies
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - labeled

jobs:
  check-outdated:
    name: Check outdated dependencies
    runs-on: ubuntu-latest
    if: github.event.label.name == 'check-outdated'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Quality - cargo outdated
        timeout-minutes: 20
        run: |
          VERSION=$(curl -s https://api.github.com/repos/kbknapp/cargo-outdated/releases/latest | jq -r '.tag_name')
          curl -sSfL "https://github.com/kbknapp/cargo-outdated/releases/download/${VERSION}/cargo-outdated-${VERSION#v}-x86_64-unknown-linux-musl.tar.gz" | \
            tar zx
          chmod +x cargo-outdated
          mv cargo-outdated ~/.cargo/bin/
          rm -rf ~/.cargo/advisory-db
          cargo outdated --exit-code 1
