# Reusable workflow: CI/CD supply chain attack pattern detection.

name: Poutine

on:
  workflow_call:

permissions: {}

jobs:
  poutine:
    name: CI/CD Supply Chain Security
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run poutine
        uses: boostsecurityio/poutine-action@84c0a0d32e8d57ae12651222be1eb15351429228 # v0.15.2
        with:
          repository: ${{ github.repository }}
