name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  prepare-artifacts:
    name: Prepare release artifacts
    # if: github.ref == 'refs/heads/main'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            rust: stable
            suffix: ''
            archive_ext: zip
          - os: macos-15-intel
            target: x86_64-apple-darwin
            rust: stable
            suffix: ''
            archive_ext: zip
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: stable
            suffix: ''
            archive_ext: tar.xz
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            rust: stable
            suffix: ''
            archive_ext: tar.xz
    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1


      - name: Build Release
        run: cargo build --release

      - name: Compress to zip (macOS)
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-15-intel' }}
        run: zip -A ${{ github.event.repository.name }}-${{ matrix.target }}.${{ matrix.archive_ext }} target/release/${{ github.event.repository.name }}

      - name: Compress to tar.xz (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm' }}
        run: tar Jcf ${{ github.event.repository.name }}-${{ matrix.target }}.${{ matrix.archive_ext }} target/release/${{ github.event.repository.name }}

      - name: List files
        run: |
          ls -alF .
          ls -alF target/release/
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target }}.${{ matrix.archive_ext }}
          path: ${{ github.event.repository.name }}-${{ matrix.target }}.${{ matrix.archive_ext }}

  release:
    name: Create a GitHub Release
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - prepare-artifacts
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # convco needs all history to create the changelog
          fetch-depth: 0

      - name: Extract version
        id: extract-version
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"

      - name: Download convco
        run: |
          git show-ref
          curl -sSfLO https://github.com/convco/convco/releases/latest/download/convco-ubuntu.zip
          unzip convco-ubuntu.zip
          chmod +x convco

      - name: Use convco to create the changelog
        run: |
          ./convco changelog -c .convco --max-versions 1 --include-hidden-sections > CHANGELOG.md
          rm convco convco-ubuntu.zip

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ github.event.repository.name }}-x86_64-unknown-linux-gnu.tar.xz
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ github.event.repository.name }}-aarch64-unknown-linux-gnu.tar.xz
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ github.event.repository.name }}-aarch64-apple-darwin.zip
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ github.event.repository.name }}-x86_64-apple-darwin.zip

      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          artifacts: '*.zip,*.tar.xz'
          bodyFile: 'CHANGELOG.md'
          token: ${{ secrets.GITHUB_TOKEN }}

  homebrew:
    name: Bump Homebrew formula
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Extract version
        id: extract-version
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"

      - uses: mislav/bump-homebrew-formula-action@ccf2332299a883f6af50a1d2d41e5df7904dd769 # v4
        if: '!contains(github.ref, ''-'')' # skip prereleases
        with:
          formula-name: tmux-backup
          homebrew-tap: graelo/homebrew-tap
          # base-branch: main
          create-pullrequest: true
          download-url: https://github.com/graelo/tmux-backup/archive/refs/tags/${{ steps.extract-version.outputs.tag-name }}.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
