# Runs Renovate to check for dependency updates.
# Triggers weekly on Monday mornings, or manually via workflow_dispatch.

name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 5' # every Friday at 16:00 UTC

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Renovate
        uses: renovatebot/github-action@b67590ea780158ccd13192c22a3655a5231f869d # v46.1.8
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
